version: '3.1'

services:

  db:
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: aiopg
      POSTGRES_USER: aiopg
      POSTGRES_PASSWORD: aiopg
